name: ✨ Feature Request
description: Suggest an enhancement or new feature for ExtraNyaa
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        
        We'd love to hear your ideas for improving ExtraNyaa! Please describe your suggestion below.

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - New anime site support (beyond Nyaa.si)
        - Additional anime database integration (beyond MAL)
        - Enhanced matching algorithms
        - New popup interface features
        - Performance improvements
        - Accessibility improvements
        - Import/Export functionality
        - Statistics and analytics
        - Other (please describe below)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve? What's currently frustrating or missing?
      placeholder: "I often visit other anime torrent sites and wish ExtraNyaa worked there too..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "Add support for Anidex.info with the same MAL integration..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there alternative approaches that might work?
      placeholder: "Maybe a generic content script that works on any torrent site..."
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: How would you (and others) use this feature?
      placeholder: |
        - When browsing Anidex, see MAL status icons
        - Quickly identify which torrents are for anime I'm watching
        - Avoid downloading duplicates of completed series
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be very useful
        - Essential for my workflow
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: "Here's a screenshot of how it might look..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've searched existing issues to make sure this hasn't been requested before
          required: true
        - label: This feature would benefit other ExtraNyaa users, not just myself
          required: false
