name: Issue Management

on:
  issues:
    types: [opened, labeled]

jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    
    steps:
      - name: Add triage label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-triage']
            });

      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `👋 Thanks for opening this issue! 
            
            We'll review it soon and get back to you. In the meantime:
            - Make sure you're using the latest version from our [releases](https://github.com/${context.repo.owner}/${context.repo.repo}/releases)
            
            This is our public release repository. For immediate support, you can also check our documentation.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });